version: "3"

services:
  r:
    image: r
    container_name: r-docs
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./:/./home/rstudio/r/
    working_dir: /home/rstudio/r/
    command: Rscript ./src/run_pipeline.R

  database:
    image: docker.pkg.github.com/open-discourse/open-discourse/database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
